# Generated by Django 4.0.3 on 2023-01-11 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOCTORS',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(default='profile_images/default.jpg', upload_to='profile_images')),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('gander', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PATIENTS',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(default='profile_images/default.jpg', upload_to='profile_images')),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('gander', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
